#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Dixmod\ShapesCalculate;

$app = new Application("dixmod console", "v1.0.0");
$app->add(new ShapesCalculate());
$app->run();

